### ISSUE TITLE
division by zero in EFT classifier

### ISSUE THREAD

**Issue by JustQJ** [Jikai0Wang/DREE#1]
There is division by zero error when using the ETF Classifier with regression task(e.g. STSB task in glue) which has one label.
` M = np.sqrt(num_classes / (num_classes-1)) * torch.matmul(P, I-((1/num_classes) * one))`

**Comment by Jikai0Wang** [comment]
As stated in the caption of Table 1 of our paper，ETF Classifiers do not support regression.
